<?php
return array(
	"" => "main/index",
	"order" => "cart/order",
	"cart" => "cart/index",
	"product/tp([0-9]+)p([0-9]+)" => "product/index/$1/$2",
	"promotion/([0-9]+)" => "main/promotion/$1",
	"profile/info" => "user/info",
	"profile" => "user/profile",
	"admin/3" => "admin/promotion",
	"admin/2" => "admin/product",
	"admin/1" => "admin/order",
	"admin" => "admin/index",
	"sign" => "user/sign",
	"constructor" => "category/constructor",
	"category/([0-9]+)/([0-9]+)/([0-9]+)" => "category/thirdcat/$1/$2/$3",
	"category/([0-9]+)/([0-9]+)" => "category/secondcat/$1/$2",
	"category/([0-9]+)" => "category/firstcat/$1",
	"category" => "category/firstcat/2",
	"info" => "info/howbuy",
	"info/howbuy" => "info/howbuy",
	"info/covid" => "info/covid",
	"info/question" => "info/question",
	"info/delivery" => "info/delivery",
	"info/pay" => "info/pay",
	"info/return" => "info/return",
	"info/claims" => "info/claims",
	"info/tablesize" => "info/tablesize",
	"info/constructor" => "info/constructor",
	"info/termsofuse" => "info/termsofuse",
	"info/privacypolicy" => "info/privacypolicy",
	"info/price" => "info/price",
);