<?php
return array(
	"" => "main/index",
	"order" => "cart/order",
	"cart" => "cart/index",
	"product/tp([0-9]+)p([0-9]+)" => "product/index/$1/$2",
	"profile/info" => "user/info",
	"profile" => "user/profile",
	"sign" => "user/sign",
	"constructor" => "category/constructor",
	"category/5" => "category/constructor",
	"category/4" => "category/best",
	"category/3" => "category/man",
	"category/2" => "category/woman",
	"category/1" => "category/new",
	"category" => "category/woman",
	"info" => "info/howbuy",
	"info/howbuy" => "info/howbuy",
	"info/covid" => "info/covid",
	"info/question" => "info/question",
	"info/delivery" => "info/delivery",
	"info/pay" => "info/pay",
	"info/return" => "info/return",
	"info/claims" => "info/claims",
	"info/tablesize" => "info/tablesize",
	"info/constructor" => "info/constructor",
	"info/termsofuse" => "info/termsofuse",
	"info/privacypolicy" => "info/privacypolicy",
	"info/price" => "info/price",
);